### ISSUE TITLE
It's work with xml file ?

### ISSUE THREAD

**Issue by nenes82** [junstyle/vscode-php-cs-fixer#152]
Hello,
For the config, can I use a xml file ? 

Regards

**Comment by junstyle** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by RoestVrijStaal** [comment]
Linking to the phpcs repo is not a valid answer.

In the readme.md of this repo, the [configuration](https://github.com/junstyle/vscode-php-cs-fixer/tree/2d8254e427fff5933570573e43d4f5399f6c4fba#configuration) lacks mentioning phpcs.xml.dist

Own tests turns out this extension does not accept xmls as config for phpcs.
