### ISSUE TITLE
"php-cs-fixer.onsave": true not working with "files.autoSave": "onFocusChange"

### ISSUE THREAD

**Issue by flamisz** [junstyle/vscode-php-cs-fixer#20]
When the `"files.autoSave": "onFocusChange"` settings is on in VS Code (it means saves automatically the changes) and you don't save the file manually, the fixer doesn't work. 

Still works on manual save.

Am I missing something?

**Comment by junstyle** [comment]
works on my vsc,  settings:
vsc1.18.1
win10

you can disable other extensions and check again, maybe have conflicts with other extensions.

**Comment by flamisz** [comment]
vsc 1.18.1
mac os High Sierra

Not working when I let autosave the file. It works when I save manually.

**Comment by mydnic** [comment]
same problem as @flamisz on mac

**Comment by junstyle** [comment]
try:
`"editor.formatOnSave": true`
and make sure
`"php-cs-fixer.documentFormattingProvider": true`

**Comment by mydnic** [comment]
thx @junstyle it works like that !

**Comment by flamisz** [comment]
Thx, it works that way

**Comment by mriverodorta** [comment]
this happens to me today, the thing that was causing the problem was that I have installed another PHP formatter **PHP Intelephense** so VS Code was executing **PHP Intelephense** instead of **php-cs-fixer**. the solution was to explicitly specify **php-cs-fixer** as the default PHP formatter in settings.json like this.

`"[php]": {
    "editor.defaultFormatter": "junstyle.php-cs-fixer"
  }`
